ANTHROPIC_BASE_URL='http://127.0.0.1:7890' \
ANTHROPIC_AUTH_TOKEN='demo' \
ANTHROPIC_DEFAULT_OPUS_MODEL='Qwen3-Coder-30B-A3B-Instruct-MLX-4bit' \
ANTHROPIC_DEFAULT_SONNET_MODEL='Qwen3-Coder-30B-A3B-Instruct-MLX-4bit' \
ANTHROPIC_DEFAULT_HAIKU_MODEL='Qwen3-Coder-30B-A3B-Instruct-MLX-4bit' \
ANTHROPIC_DEFAULT_OPUS_MODEL='Qwen3-Coder-Next-MLX-6bit' \
ANTHROPIC_DEFAULT_SONNET_MODEL='Qwen3-Coder-Next-MLX-6bit' \
ANTHROPIC_DEFAULT_HAIKU_MODEL='Qwen3-1.7B-MLX-4bit' \
API_TIMEOUT_MS=3000000 \
CLAUDE_CODE_DISABLE_NONESSENTIAL_TRAFFIC=1 \
uv run chatviz --upstream http://localhost:8765 claude


